import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exams Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Exams creator app!
        </h1>
        <br></br>
        <h3 className={styles.title}>Please log in!</h3>
        <h3>Or create an accuount</h3>
        <br></br>
        <div className={styles.grid}>
          <a href="login" className={styles.card}>
            <h2>I'm a student &rarr;</h2>
          </a>

          <a href="login" className={styles.card}>
            <h2>I'm a teacher &rarr;</h2>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
